### ISSUE TITLE
Bug instantiating gimp file with GimpDocument.  Seems like its an issue with changes to str and bytes.

### ISSUE THREAD

**Issue by ismaelharunid** [FHPythonUtils/GimpFormats#2]
```
from gimpformats.gimpXcfDocument import GimpDocument
imagepath = 'borders.xcf'
doc = GimpDocument(imagepath)
```
Produces the follow dump:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/gimpXcfDocument.py", line 65, in __init__
    self.load(fileName)
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/gimpXcfDocument.py", line 82, in load
    self.decode(data)
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/gimpXcfDocument.py", line 121, in decode
    self._propertiesDecode(ioBuf)
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/GimpIOBase.py", line 703, in _propertiesDecode
    self._propertyDecode(propertyType, ioBuf.getBytes(dataLength))
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/GimpIOBase.py", line 441, in _propertyDecode
    self._guidelinesDecode(data)
  File "/home/ismael/miniconda3/lib/python3.7/site-packages/gimpformats/GimpIOBase.py", line 286, in _guidelinesDecode
    isVertical = struct.unpack(">B", data[index])[0] == 2
TypeError: a bytes-like object is required, not 'int'
```

It looks like it's likely caused by changes to bytes and str and between old and newer version of python.  I'll update this "issue" as I get more detailed information.  In the meantime, I'm sure you must already know or is this possibly a dead project?

**Comment by FredHappyface** [comment]
If you wanna make a pull request that'd be very much appreciated. Also it might be worth taking a look at #1 as this is where my thoughts are regarding the future of the project

**Comment by FredHappyface** [comment]
Think I've fixed it 

If this is still broken then can you send me the xcf file and I'll take another look sometime

Thanks
